FROM python:3.11.4

# update packages
RUN apt-get -qq update
RUN apt-get install --yes apache2 apache2-dev
RUN pip install mod_wsgi

RUN mkdir /code
WORKDIR /code

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/

CMD mod_wsgi-express start-server /code/restaurant_site/restaurant_site/wsgi.py --user www-data --group www-data